Dedenpencies update and implementation of smart actions
Mik13/nuki-bridge-api pull request #24
Opened 2020-11-15 16:18 UTC by carlptr

- Replaced unmaintained lib request with got
- Updated dependencies with npm audit fix --force
- Added new methods "lock" and "unlock" in Nuki class to use smart actions of Nuki API

2020-11-15 17:46 UTC, Mik13 requested changes
Thank you very much, this looks very good. Please change the few things pointed out and I will happily merge it.

2020-11-15 17:46 UTC, Mik13 commented on lib/bridge.js
> +//var request = require('request-promise');
Could you please remove the line? We won't need it anymore

2020-11-15 17:46 UTC, Mik13 commented on lib/bridge.js
> +
Please move the JSON to the Error-string, so the user can decide if they log the error or not, like:
`throw new Error('Did not receive a list of nukis! Response: ' + JSON.stringify(nukis));`

2020-11-15 17:46 UTC, Mik13 commented on lib/bridge.js
>          throw new Error('did not receive a list of nukis');
Same as last comment

2020-11-15 17:46 UTC, Mik13 commented on lib/bridge.js
> +
And please remove empty lines at the start or end of a block.

2020-11-15 17:46 UTC, Mik13 commented on lib/nuki.js
> +//var request = require('request-promise');
Remove this line please

2020-11-16 07:02 UTC, carlptr commented
Thanks for the helpful review. I made the requested changes.

2020-11-20 07:11 UTC, Mik13 commented
Thank you very much! I've put your commits into master and published version 1.7.0 to npm.

2020-11-20 07:11 UTC, closed without merging